<?php

namespace Billfold\SiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class pagesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Billfold\SiteBundle\Controller\pagesController();
        return $instance;
    }
}
